config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :views
  devise_for :users
  resources :users
  root 'pages#home'
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :organizations
end

app/models/gender.rb
class Gender < ApplicationRecord
has_many :users, through: :target_genders
has_many :target_genders
end

app/models/host.rb
class Host < ApplicationRecord
end

app/models/kink_interest.rb
class KinkInterest < ApplicationRecord
end

app/models/kink_role.rb
class KinkRole < ApplicationRecord
  has_many :users, through: :target_kink_roles
  has_many :target_kink_roles
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :users, through: :user_locations
  has_many :user_locations
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :events
end

app/models/target_gender.rb
class TargetGender < ApplicationRecord
  belongs_to :user
  belongs_to :gender
end

app/models/target_kink_role.rb
class TargetKinkRole < ApplicationRecord
  belongs_to :user
  belongs_to :kink_role
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :gender
  has_one :kink_interest
  has_one :kink_role

  has_many :user_locations
  has_many :locations, through: :user_locations

  has_many :target_genders
  has_many :genders, through: :target_genders

  has_many :target_kink_roles
  has_many :kink_roles, through: :target_kink_roles
  
  has_and_belongs_to_many :events
end

app/models/user_location.rb
class UserLocation < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.fetch(:host, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/form/_gender.html.erb
<%= f.label :gender, 'Transgender Woman' %>
<%= f.radio_button :gender, 'transgender woman' %>
<%= f.label :gender, 'Transgender Man' %>
<%= f.radio_button :gender, 'transgender man' %>
<%= f.label :gender, 'Cis Woman' %>
<%= f.radio_button :gender, 'cis woman' %>
<%= f.label :gender, 'Cis Man' %>
<%= f.radio_button :gender, 'cis man' %>
<%= f.label :gender, 'Non-Binary, Gender Fluid, Gender Queer' %>
<%= f.radio_button :gender, 'non-binary, gender fluid, gender queer' %>
<%= f.label :gender, 'None of the above apply' %>
<%= f.radio_button :gender, 'none of the above apply' %>

app/views/layouts/_alerts.html.erb
<div class="alert">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolySpeedDating</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/myusers/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/myusers/new.html.erb
<h1>Add a new user:</h1>

  <%= form_for [@user] do |f| %>
  <h2>Personal Demographics</h2>
<div class="form-group">
  <%= f.label :display_name %>
  <%= f.text_field :display_name %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  </div>
  <%= f.label :age %>
  <%= f.number_field :age %>
  </br></br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  </br></br>

  <h2> Do you want to be contacted with events and updates?</h2>
  <%= f.label :email_list, 'Yes' %>
  <%= f.radio_button :email_list, 'true' %>
  <%= f.label :email_list, 'No' %>
  <%= f.radio_button :email_list, 'false' %>

  </br></br>
  <h2>Did anyone refer you?
    <%= f.label :referral %>
    <%= f.text_field :referral %>
    <%= f.label :comments %>
    <%= f.text_area(:comments, cols: 30, rows: 10)  %>

    <h2>Gender Section</h2>
    <%= f.select(:gender_id, @gender) %>

    <h2>Kink Section</h2>

    <%= f.label :kinky, 'Yes' %>
    <%= f.radio_button :kinky, 'true' %>
    <%= f.label :kinky, 'No' %>
    <%= f.radio_button :kinky, 'false' %>
  </br>
  </br>
  <%= f.select(:kink_interest_id, @kink_interest) %>
  </br>

  <%= f.select(:kink_role_id, @kink_role) %>
  <h3> Target kink roles are </h3>

  <%= f.collection_check_boxes(:kink_role_ids, KinkRole.all, :id, :kink_role) %>

  <h2> Dates Group Section </h2>
  dates groups
  <%= f.label :dates_groups, 'Yes' %>
  <%= f.radio_button :dates_groups, 'true' %>
  <%= f.label :dates_groups, 'No' %>
  <%= f.radio_button :dates_groups, 'false' %>
  whole group
  <%= f.label :must_match_whole_group, 'Yes' %>
  <%= f.radio_button :must_match_whole_group, 'true' %>
  <%= f.label :must_match_whole_group, 'No' %>
  <%= f.radio_button :must_match_whole_group, 'false' %>

  <h2>Event Section </h2>
  friend dates
  <%= f.label :friend_dates, 'Yes' %>
  <%= f.radio_button :friend_dates, 'true' %>
  <%= f.label :friend_dates, 'No' %>
  <%= f.radio_button :friend_dates, 'false' %>

  </br>
  stationary
  <%= f.label :stationary, 'Yes' %>
  <%= f.radio_button :stationary, 'true' %>
  <%= f.label :stationary, 'No' %>
  <%= f.radio_button :stationary, 'false' %>


  <h3> Target Age </h3>
  <%= f.label :target_age_floor %>
  <%= f.number_field :target_age_floor %>
  <%= f.label :target_age_ceiling %>
  <%= f.number_field :target_age_ceiling %>

  <h3> Target Genders </h3>
  <div class="form-group form-check">
  <%= f.collection_check_boxes(:gender_ids, Gender.all, :id, :gender) %>
  </div>

  <h3> Date Locations </h3>
  <%= f.collection_check_boxes(:location_ids, Location.all, :id, :location) %>

  <p><%= f.submit %></p>
  <% end %>

app/views/pages/home.html.erb
<div class="banner">
  <h1>Speed Dating</h1>
  <%= button_to 'Sign up', new_user_registration_path %>
  <%= button_to 'Sign in', new_user_session_path %>
</div>
<div>
  <h2>Checkout Upcoming Events</h2>
</div>
<<div class="list">
  <ul>
    <li> 01/01/20 - Event One - Portland, Oregon </li>
    <li> 01/01/20 - Event Two - Beulla, Main </li>
    <li> 01/01/20 - Event Three - Passamaquady, Ohio </li>
    <li> 01/01/20 - Event Four - Neverland, Somewhere </li>
    <li> 01/01/20 - Event Five - Middle of Nowhere, Texas </li>
    <li> 01/01/20 - Event Six - Among the Cows, Oregon </li>
    <li> 01/01/20 - Event Seven - I am out of ideas, USA </li>
    </ul>
</div>